# Generated by Django 3.0.4 on 2020-04-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='addresss',
            new_name='address',
        ),
    ]
